repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.5.0"
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: mixed-line-ending
- repo: https://github.com/hhatto/autopep8
  rev: "v2.0.4"
  hooks:
  - id: autopep8
- repo: https://github.com/pycqa/isort
  rev: "5.12.0"
  hooks:
  - id: isort
- repo: https://github.com/codespell-project/codespell
  rev: "v2.2.6"
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli
